const baseCfg = require('./karma.config'),
	pkg = require('../package.json')

module.exports = function(config) {
	baseCfg(config)
	config.set({
		browsers: Object.keys(browsers),
		customLaunchers: browsers,
		reporters: ['spec', 'coverage', 'saucelabs'],
		sauceLabs: {
			testName: `${pkg.name} unit tests`,
			username: process.env.SAUCE_USERNAME,
			accessKey: process.env.SAUCE_ACCESS_KEY,
			tunnelIdentifier: 'autoGeneratedTunnelID',
			tags: ['v' + pkg.version],
			public: 'public'
		},
		captureTimeout: 300 * 1000,
		browserNoActivityTimeout: 300 * 1000
	})
}

const browsers = {
	WIN_Chrome: {
		base: 'SauceLabs',
		displayName: 'Chrome (Windows 7)',
		browserName: 'chrome',
		platform: 'Windows 7'
	},
	WIN_Firefox: {
		base: 'SauceLabs',
		displayName: 'Firefox (Windows 7)',
		browserName: 'firefox',
		platform: 'Windows 7',
		version: '44'
	},
	OXS_Safari: {
		base: 'SauceLabs',
		displayName: 'Safari (OSX 10.10)',
		browserName: 'safari',
		platform: 'OS X 10.10'
	},
	IE11: {
		base: 'SauceLabs',
		displayName: 'IE11 (Windows 8.1)',
		browserName: 'internet explorer',
		platform: 'Windows 8.1',
		version: '11'
	},
	IE10: {
		base: 'SauceLabs',
		displayName: 'IE10 (Windows 8)',
		browserName: 'internet explorer',
		platform: 'Windows 8',
		version: '10'
	},
	IE9: {
		base: 'SauceLabs',
		displayName: 'IE9 (Windows 7)',
		browserName: 'internet explorer',
		platform: 'Windows 7',
		version: '9'
	},
	IE8: {
		base: 'SauceLabs',
		displayName: 'IE8 (Windows 7)',
		browserName: 'internet explorer',
		platform: 'Windows 7',
		version: '8'
	},
	IE7: {
		base: 'SauceLabs',
		displayName: 'IE7 (Windows XP)',
		browserName: 'internet explorer',
		platform: 'Windows XP',
		version: '7'
	},
	IE6: {
		base: 'SauceLabs',
		displayName: 'IE6 (Windows XP)',
		browserName: 'internet explorer',
		platform: 'Windows XP',
		version: '6'
	}
}
